export * from './authentication/Login';
export * from './authentication/RegisterPage';
export * from './externo/Externo';
export * from './favourites/FavouritesSeller';
export * from './home/Home';
export * from './other/Denied';
export * from './perfil/Comprador';
export * from './perfil/Vendedor';
export * from './perfil/UserProfile';
export * from './test/Test';
// export * from './user/UserAdmin';