name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Detener la aplicación existente (si está corriendo)
            sudo pkill main || true

            # Navegar al directorio del proyecto
            cd /home/jeaqhbo/Hackathon/Hackathon

            # Resetear los cambios locales y hacer pull de la rama backend
            sudo git reset --hard
            sudo git pull origin backend

            # Compilar el proyecto
            sudo go build -o tmp/main cmd/main.go

            # Ejecutar el backend
            nohup ./tmp/main > tmp/server.log 2>&1 &
          EOF
